### ISSUE TITLE
Sometimes two dots are selected

### ISSUE THREAD

**Issue by timkoers** [MatthewTamlin/SlidingIntroScreen#1]
Sometimes when the activity just started, two dots are selected.
In this case the first and the last dot.
I think you should implement somekind of check to make sure that only 1 dot is selected. When setting another dot selected the dots are being displayed correctly.

**Comment by MatthewTamlin** [comment]
Are you extending IntroActivity or implementing SelectionIndicator by itself? I fixed the problem in IntroActivity by calling `selectionIndicator.redrawDots()` at the end of `onCreate(Bundle)`. I'll work on a permanent fix, but in the meantime try calling `redrawDots()` somewhere after instantiating and configuring SelectionIndicator.

**Comment by MatthewTamlin** [comment]
Fixed in version 1.1.0.

**Comment by timkoers** [comment]
That fixed the issue in my code too. Thanks!

 

Van: MatthewTamlin [mailto:notifications@github.com] 
Verzonden: donderdag 3 maart 2016 21:59
Aan: MatthewTamlin/SlidingIntroScreen <SlidingIntroScreen@noreply.github.com>
CC: timkoers <tim.koers@live.nl>
Onderwerp: Re: [SlidingIntroScreen] Sometimes two dots are selected (#1)

 

Are you extending IntroActivity or implementing SelectionIndicator by itself? I fixed the problem in IntroActivity by calling selectionIndicator.redrawDots() at the end of onCreate(Bundle). I'll work on a permanent fix, but in the meantime try calling redrawDots() somewhere after instantiating and configuring SelectionIndicator.

**Comment by MatthewTamlin** [comment]
Issue not actually fixed. Just discovered my "permanent fix" has disabled all animations. Hotfix coming shortly.

**Comment by MatthewTamlin** [comment]
Bug fixed permanently (hopefully) in release 1.2.0 (available now).
